version: "3.3"
services:
  db:
    image: arm64v8/mysql:8.1.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "endrnce"
      # So you don"t have to use root, but you can if you like
      MYSQL_USER: "test"
      # You can use whatever password you like
      MYSQL_PASSWORD: "root"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "root"
    ports:
      - "3306:3306"
    volumes:
      - my-db:/var/lib/mysql
# Names our volume
volumes:
  my-db: